#!/bin/sh

if [ ! -e debian/control ] ; then
    echo "$(basename ${PWD}): not a debian package"
    exit 0
fi

DIR=$(dirname "$(readlink -f "$0")")
PUSH=

git diff-index --quiet HEAD --
if [ $? -ne 0 ] ; then
    echo "Local git tree has changes"
    exit 1
fi

for CHECK in $DIR/checks/* ; do
    NAME=$(basename "$CHECK")
    echo "##### $NAME #####"
    OUT=$($CHECK)
    STATUS=$?
    if [ $STATUS -eq 0 ] ; then
        if [ -n "$OUT" ] ; then
            if $DIR/commit "$OUT" ; then
                PUSH=1
            fi
        fi
    else
        echo "ERROR: $OUT"
    fi
done

if [ -n "$PUSH" ] ; then
    echo "Pushing..."
#    git push
fi
