#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "$0 <repository_name>"
    exit 1
fi

REPO=$1
URL=https://salsa.debian.org

DIR=$(dirname "$(readlink -f "$0")")
TMP=$(mktemp -d)

echo "############## $REPO ##############"

pushd "$TMP" >/dev/null

rm -rf repo
git clone "${URL}/${REPO}" repo >/dev/null 2>&1
cd repo

$DIR/check-all

cd ..
popd >/dev/null

rm -rf "$TMP"
