#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "$0 <message>"
    exit 1
fi

MESSAGE=$1

if [ -n "$(git diff)" ] ; then
    CHANGELOG=$(dpkg-parsechangelog)

    cat debian/changelog | grep '^ --' | wc -l | grep -q "^1$"
    ONE_ENTRY=$?

    echo "$CHANGELOG" | grep -q '^Distribution: UNRELEASED$'
    UNRELEASED=$?

    echo "$CHANGELOG" | grep '^  ' | sed 's/   \* //' | grep -F -q "$MESSAGE"
    PRESENT=$?

    if ! (
            ([ $UNRELEASED -eq 0 ] && [ $PRESENT -eq 0 ]) || \
            ([ $ONE_ENTRY -eq 0 ] && [ $UNRELEASED -eq 0 ])
         ); then
        dch --no-auto-nmu "$MESSAGE"
    fi
    git add debian/
    git commit -m "$MESSAGE"
    git --no-pager show
    exit 0
fi

exit 1
