#!/bin/bash

if [ "$#" -lt 1 ]; then
    echo "$0 <message> [--test]"
    exit 1
fi

MESSAGE=$1

if [ -n "$(git diff)" ] ; then
    CHANGELOG=$(dpkg-parsechangelog)

    cat debian/changelog | grep '^ --' | wc -l | grep -q "^1$"
    ONE_ENTRY=$?

    echo "$CHANGELOG" | grep -q '^Distribution: UNRELEASED$'
    UNRELEASED=$?

    echo "$CHANGELOG" | grep '^  ' | sed 's/   \* //' | grep -F -q "$MESSAGE"
    PRESENT=$?

    if ! (
            ([ $UNRELEASED -eq 0 ] && [ $PRESENT -eq 0 ]) || \
            ([ $ONE_ENTRY -eq 0 ] && [ $UNRELEASED -eq 0 ])
         ); then

        MAINTAINER=$(grep-dctrl -n -F Maintainer '' -s Maintainer debian/control)
        case $MAINTAINER in
            *debian-multimedia@lists.debian.org*) ;;
            *pkg-multimedia-maintainers@lists.alioth.debian.org*) ;;
            *)
                dch --no-auto-nmu "$MESSAGE"
            ;;
        esac
    fi
    if [ $2 != "--test" ] ; then
        git add debian/
        git commit -m "$MESSAGE"
        git --no-pager show
    fi
    exit 0
fi

exit 1
