#!/bin/bash

set -e

sed -i "/^X-Python3-Version: *>= *3\\.[0-5].*$/d" debian/control
sed -i "/^X-Python3-Version: *>> *3\\.[0-4].*$/d" debian/control
echo "d/control: Remove ancient X-Python3-Version field"
