#!/bin/bash

set -e

if [ ! -d "debian/tests" ] ; then
    echo "No autopkgtests"
    exit 0
fi

find debian/tests -name '*' -type f -print0 |
    while IFS= read -r -d $'\0' FILE; do
        sed -i 's/$ADTTMP/$AUTOPKGTEST_TMP/g' "$FILE" 2>/dev/null
        sed -i 's/${ADTTMP}/${AUTOPKGTEST_TMP}/g' "$FILE" 2>/dev/null
    done
echo "d/tests: Use AUTOPKGTEST_TMP instead of ADTTMP"
