#!/bin/bash

# Debian Multimedia Team
if grep-dctrl -q -F Maintainer "debian-multimedia@lists.debian.org" debian/control ; then
    sed -i "s#\(^Maintainer:\).*#\1 Debian Multimedia Maintainers <debian-multimedia@lists.debian.org>#g" debian/control
    echo "d/control: Unify Maintainer field to Debian Multimedia Maintainers"
fi
if grep-dctrl -q -F Maintainer "pkg-multimedia-maintainers@lists.alioth.debian.org" debian/control ; then
    sed -i "s#\(^Maintainer:\).*#\1 Debian Multimedia Maintainers <debian-multimedia@lists.debian.org>#g" debian/control
    echo "d/control: Change Maintainer from @lists.alioth.debian.org to @lists.debian.org"
fi
