#!/bin/bash

if grep-dctrl -q -F Build-Depends 'python3-sphinx' debian/control || 
   grep-dctrl -q -F Build-Depends-Indep 'python3-sphinx' debian/control
   then
    sed -i "s#\([[:space:]]\|^\)sphinx-build\([[:space:]]\|$\)#\1python3 -m sphinx\2#g" debian/rules
    echo "Use 'python3 -m sphinx' instead of sphinx-build for building docs"
fi
