#!/bin/bash

#exit 0

set -e

VERSION=$(grep-dctrl -F Source '' debian/control | grep '^Standards-Version' | sed 's/.*: *//')
OLD_VERSION=$VERSION

if [ "$VERSION" == "4.1.0" ] ; then
    # 4.4: debian/changelog must exists ##
    if [ -a "debian/changelog" ] ; then
        VERSION="4.1.1"
    fi
fi

if [ "$VERSION" == "4.1.1" ] ; then
    # 3.1.1: -offensive suffix ## TODO
    # 10.2: private shared objects ## TODO
    # 10.4: Perl shebang, this was relaxed later so skip it
    echo -n
fi

if [ "$VERSION" == "4.1.2" ] ; then
    NO=

    # 5.6.26: Confidentiality in Vcs-* ## TODO
    VCS_BROWSER=$(grep-dctrl -n -F Vcs-Browser '' -s Vcs-Browser debian/control)
    VCS_URI=$(grep-dctrl -n -F Vcs-Uri '' -s Vcs-Browser debian/control)
    if [ "$VCS_BROWSER" != "" && ! "$VCS_BROWSER" ~= "https://" ] ; then
        NO=no
    fi

    # 9.3.3.1: /etc/default DISABLED=yes is obsolete ## TODO

    if [ "$NO" == "" ] ; then
        echo -n
#        VERSION="4.1.3"
    fi
fi

if [ "$VERSION" == "4.1.3" ] ; then
    # 9.1.2: /usr/local permission ## TODO
#    VERSION="4.1.4"
    echo -n
fi

if [ "$VERSION" == "4.1.4" ] ; then
    VERSION="4.1.5"
fi

if [ "$VERSION" == "4.1.5" ] ; then
    # 4.9: Verbose TODO
#    VERSION="4.2.0"
    echo -n
fi

if [ "$VERSION" == "4.2.0" ] ; then
    # 10.4: Just relaxed Perl shebang requirement
    VERSION="4.2.1"
fi

if [ "$VERSION" == "4.3.0" ] ; then
    # 4.9: Use debhelper
    if grep-dctrl -n -F Build-Depends 'debhelper' -s Build-Depends debian/control >/dev/null ||
            grep-dctrl -n -F Build-Depends 'debhelper-compat' -s Build-Depends debian/control >/dev/null
	    then
        VERSION="4.4.0"
    fi
fi

if [ "$VERSION" == "4.4.0" ] ; then
    # 5.6.26: A package control file must not have more than one Vcs-<type> field.
    COUNT=$(grep '^Vcs-' debian/control | grep -v 'Vcs-Browser' | wc -l)
    if [ "$COUNT" -lt "2" ] ; then
        VERSION="4.4.1"
    fi
fi

if [ "$VERSION" != "4.4.1" ] ; then
    exit 0
fi

if [ "$OLD_VERSION" != "$VERSION" ] && [ -a debian/changelog ] ; then
    sed -i "/ UNRELEASED;/,/^ --/{s/Bump Standards-Version to .*/Bump Standards-Version to $VERSION./g}" debian/changelog
fi

sed -i "s#\(^Standards-Version:\).*#\1 $VERSION#g" debian/control
echo "Bump Standards-Version to $VERSION"
