#!/bin/bash

sed -i "s#http://\(github.com/\)#https://\1#g" debian/watch
sed -i "s#http://\(tarballs.openstack.org/\)#https://\1#g" debian/watch
sed -i "s#http://\(pypi.debian.net/\)#https://\1#g" debian/watch

echo "d/watch: Use https protocol"
